version: '3.1'
services:
  product-services-db:
    image: postgres:9.6.8-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: p4SSW0rd
    ports:
      - 5432:5432
  yh-product-services:
    depends_on:
      - product-services-db
    image: yh-product-services
    links:
      - product-services-db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=product-services-db
      - DATABASE_PORT=5432
      - DATABASE_NAME=dbcadastro
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=p4SSW0rd
    volumes:
      - vl-product-services-db:/var/lib/postgresql/data

volumes:
  vl-product-services-db:
    driver: local